AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        login:
            type: string
            length: 255
            unique: true
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        image:
            type: string
            length: '512'
        movieTypes:
            type: string
            length: '512'
        movieNumber:
            type: integer
        createdAt:
            type: datetime
        editedAt:
            type: datetime
    lifecycleCallbacks: {  }
